server:
  port: 80

spring:
  datasource:
    url: jdbc:mysql://192.168.123.102/demo?useUnicode=true&characterEncoding=UTF-8&serverTimezone=GMT%2B8
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  data:
    redis:
      host: 192.168.123.102
      password: redis
      port: 6379
  main:
    allow-circular-references: true